FROM nginmesh/ngx_http_collector_module-base:dev as module_builder
MAINTAINER Sehyo Chang "sehyo@nginx.com"

# this is coming from context which is from /build/context not root of the source
ADD ./collector-ngx /src/collector-ngx
ADD ./collector-transport /src/collector-transport
ADD ./collector-tests /src/collector-tests
ADD ./module /src/module
ADD ./test /src/test
RUN cd /src;make nginx-module

FROM nginmesh/nginx-dev:1.13.7
COPY --from=module_builder /src/nginx/nginx-linux/objs/ngx_http_collector_module.so /etc/nginx/modules
COPY --from=module_builder /src/test/config/nginx.conf /etc/nginx/nginx.conf
COPY --from=module_builder /src/test/config/conf.d/http.conf /etc/nginx/conf.d/http.conf
COPY --from=module_builder /src/test/config/conf.d/remote.conf /etc/nginx/conf.d/remote.conf
COPY --from=module_builder /src/test/services/http.js /test/http.js
COPY --from=module_builder /src/test/deploy.sh /test/deploy.sh

